"""Add Settings model

Revision ID: 522decdd12c1
Revises: df85d1761fce
Create Date: 2025-12-04 15:59:14.648429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522decdd12c1'
down_revision = 'df85d1761fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
