"""Create product and variants tables

Revision ID: 8822feb7cda8
Revises: ae00b81ecd02
Create Date: 2025-11-16 17:11:42.075839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8822feb7cda8'
down_revision = 'ae00b81ecd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('description_template_pl', sa.Text(), nullable=True),
    sa.Column('description_template_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('image2_url', sa.String(length=255), nullable=False),
    sa.Column('image3_url', sa.String(length=255), nullable=False),
    sa.Column('image4_url', sa.String(length=255), nullable=False),
    sa.Column('image5_url', sa.String(length=255), nullable=False),
    sa.Column('image6_url', sa.String(length=255), nullable=False),
    sa.Column('image7_url', sa.String(length=255), nullable=False),
    sa.Column('image8_url', sa.String(length=255), nullable=False),
    sa.Column('image9_url', sa.String(length=255), nullable=False),
    sa.Column('image10_url', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('link2_url', sa.String(length=255), nullable=True),
    sa.Column('link3_url', sa.String(length=255), nullable=True),
    sa.Column('link4_url', sa.String(length=255), nullable=True),
    sa.Column('link5_url', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    op.drop_table('product')
    # ### end Alembic commands ###
