"""Allow nullable images in variant table

Revision ID: cc8278c9805b
Revises: 522decdd12c1
Create Date: 2025-12-04 19:09:51.543044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8278c9805b'
down_revision = '522decdd12c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image2_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image4_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image5_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image6_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image7_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image8_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image9_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image10_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.alter_column('image10_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image9_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image8_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image7_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image6_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image5_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image4_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image2_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
